from scrapy.cmdline import execute

'''
运行测试
正式运行前记得 开启 html_text 字段的注释
'''

# execute('scrapy crawl stockstar.com'.split()) #
# execute('scrapy crawl hexun.com'.split()) #
# execute('scrapy crawl ifeng.com'.split()) #
# execute('scrapy crawl mobile.163.com'.split()) #
# execute('scrapy crawl caijing.com.cn'.split()) #
# execute('scrapy crawl stcn.com'.split()) #
# execute('scrapy crawl pedaily.cn'.split()) #
# execute('scrapy crawl sina.com.cn'.split()) #
# execute('scrapy crawl cnfol.com'.split())
# execute('scrapy crawl cnfol.hk.com'.split())
# execute('scrapy crawl sohu.com'.split())
# execute('scrapy crawl jrj.com.cn'.split())
# execute('scrapy crawl cnstock.com'.split())
# execute('scrapy crawl huxiu.com'.split())
# execute('scrapy crawl wallstreetcn.com'.split())
# execute('scrapy crawl eeo.com.cn'.split())
# execute('scrapy crawl cfi.cn'.split())
# execute('scrapy crawl qq.com'.split())
# execute('scrapy crawl cs.com.cn'.split())
# execute('scrapy crawl cyzone.cn'.split())
# execute('scrapy crawl gelonghui.com'.split())#降到1.5爬取
# execute('scrapy crawl qhrb.com.cn'.split())
# execute('scrapy crawl xueqiu.com'.split())#未完成
# execute('scrapy crawl csindex.com.cn'.split())
# execute('scrapy crawl cn.investing.com'.split())
# execute('scrapy crawl finet.hk'.split())
# execute('scrapy crawl donews.com'.split())
# execute('scrapy crawl pingwest.com'.split())
# execute('scrapy crawl cn.technode.com'.split())
# execute('scrapy crawl jingmeiti.com'.split())
# execute('scrapy crawl chinaventure.com.cn'.split())
# execute('scrapy crawl nbd.com.cn'.split())
# execute('scrapy crawl cb.com.cn'.split())
# execute('scrapy crawl capitalweek.com.cn'.split())
# execute('scrapy crawl amoney.com.cn'.split())
# execute('scrapy crawl xcf.cn'.split())
# execute('scrapy crawl iceo.com.cn'.split())
# execute('scrapy crawl tmtpost.com'.split())
# execute('scrapy crawl hongzhoukan.com'.split())
# execute('scrapy crawl eastmoney.com'.split())
# execute('scrapy crawl ofweek.com'.split())
# execute('scrapy crawl cria.org.cn'.split())
# execute('scrapy crawl sac.net.cn'.split())
# execute('scrapy crawl iresearch.cn'.split())
# execute('scrapy crawl shfe.com.cn'.split())
# execute('scrapy crawl pconline.com.cn'.split())
# execute('scrapy crawl cheaa.com'.split())
# execute('scrapy crawl jdxfw.com'.split())
# execute('scrapy crawl chinadrink.net'.split())
# execute('scrapy crawl iachina.cn'.split())
# execute('scrapy crawl bicpa.org.cn'.split())
# execute('scrapy crawl cicpa.org.cn'.split())
# execute('scrapy crawl gzicpa.org.cn'.split())
# execute('scrapy crawl szicpa.org'.split())
# execute('scrapy crawl capc.org.cn'.split())
# execute('scrapy crawl catcm.org.cn'.split())
# execute('scrapy crawl ccta.org.cn'.split())
# execute('scrapy crawl amac.org.cn'.split())
# execute('scrapy crawl cansi.org.cn'.split())
# execute('scrapy crawl ic-ceca.org.cn'.split())
# execute('scrapy crawl china-cotton.org'.split())
# execute('scrapy crawl chinaisa.org.cn'.split())
# execute('scrapy crawl cfachina.org'.split())#降速获取
# execute('scrapy crawl chinania.org.cn'.split())
# execute('scrapy crawl caam.org.cn'.split())
# execute('scrapy crawl zhiding.cn'.split())
# execute('scrapy crawl 800hr.com'.split())
# execute('scrapy crawl chyxx.com'.split())
# execute('scrapy crawl pack.cn'.split())
# execute('scrapy crawl ccidnet.com'.split())
# execute('scrapy crawl cfbond.com'.split())
# execute('scrapy crawl glassinfo.com.cn'.split())
# execute('scrapy crawl chinadaily.com.cn'.split())
# execute('scrapy crawl xinm123.com'.split())
# execute('scrapy crawl sli.top'.split())
# execute('scrapy crawl ncw365.com'.split())
# execute('scrapy crawl xtxh.net'.split())
# execute('scrapy crawl ccfa.com.cn'.split())
# execute('scrapy crawl 3bf.cc'.split())
# execute('scrapy crawl ine.cn'.split())
# execute('scrapy crawl china-cba.net'.split())
# execute('scrapy crawl tbankw.com'.split())
# execute('scrapy crawl tech-food.com'.split())
# execute('scrapy crawl ksjx.com.cn'.split())
# execute('scrapy crawl menet.com.cn'.split())
# execute('scrapy crawl co188.com'.split())
# execute('scrapy crawl gmw.cn'.split())
# execute('scrapy crawl 7hcn.com'.split())
# execute('scrapy crawl coalchina.org.cn'.split())
# execute('scrapy crawl infzm.com'.split())
# execute('scrapy crawl techweb.com.cn'.split())
# execute('scrapy crawl csteelnews.com'.split())
# execute('scrapy crawl zgsyqx.com'.split())
# execute('scrapy crawl aweb.com.cn'.split())
# execute('scrapy crawl c114.com.cn'.split())
# execute('scrapy crawl cfen.com.cn'.split())
# execute('scrapy crawl knowledgeatwharton.com.cn'.split())
# execute('scrapy crawl xinhuanet.com'.split())
# execute('scrapy crawl nmgnews.com.cn'.split())
# execute('scrapy crawl dahe.cn'.split())
# execute('scrapy crawl cngold.org'.split())
# execute('scrapy crawl big5.ocn.com.cn'.split())
# execute('scrapy crawl yunnan.cn'.split())
# scrapy crawl sxgov.cn'.split())
# executeexecute('scrapy crawl hebnews.cn'.split())
# # execute('scrapy crawl p5w.net'.split())
# # execute('('scrapy crawl 17ok.com'.split())
# execute('scrapy crawl qianlong.com'.split())
# execute('scrapy crawl financial.ynet.com'.split())
# execute('scrapy crawl china.com'.split())
# execute('scrapy crawl workercn.cn'.split())
# execute('scrapy crawl hnrb.voc.com.cn'.split())
# execute('scrapy crawl mysteel.com'.split())
# execute('scrapy crawl ce.cn'.split())
# execute('scrapy crawl southcn.com'.split())
# execute('scrapy crawl 10jqka.com.cn'.split())
# execute('scrapy crawl zhitongcaijing.com'.split())
# execute('scrapy crawl wabei.cn'.split())
# execute('scrapy crawl cnlist.com'.split())
# execute('scrapy crawl texnet.com.cn'.split())
# execute('scrapy crawl yicai.com'.split())
# execute('scrapy crawl texnet.com.cn'.split())
# execute('scrapy crawl laoyaoba.com'.split())
# execute('scrapy crawl elecfans.com'.split())
# execute('scrapy crawl mydrivers.com'.split())
# execute('scrapy crawl 21ic.com'.split())
# execute('scrapy crawl jwview.com'.split())
# execute('scrapy crawl guandian.cn'.split())
# execute('scrapy crawl thepaper.cn'.split())
# execute('scrapy crawl abi.com.cn'.split())
# execute('scrapy crawl bbtnews.com.cn'.split())
# execute('scrapy crawl southmoney.com'.split())
# execute('scrapy crawl ccement.com'.split())
# execute('scrapy crawl zqrb.cn'.split())
# execute('scrapy crawl chineseshipping.com.cn'.split())
# execute('scrapy crawl sci99.com'.split())
# execute('scrapy crawl gasgoo.com'.split())
# execute('scrapy crawl 99it.com'.split())
# execute('scrapy crawl 96369.net'.split())
# execute('scrapy crawl chinaipo.com'.split())
# execute('scrapy crawl emoney.cn'.split())
# execute('scrapy crawl china5e.com'.split())
# execute('scrapy crawl takungpao.com'.split())
# execute('scrapy crawl jiemian.com'.split())
# execute('scrapy crawl ccaonline.cn'.split())
# execute('scrapy crawl linkshop.com'.split())
# execute('scrapy crawl d1ev.com'.split())
# execute('scrapy crawl winshang.com'.split())
# execute('scrapy crawl bioon.com'.split())
# execute('scrapy crawl qianzhan.com'.split())
# execute('scrapy crawl sse.net.cn'.split())
# execute('scrapy crawl zgsyb.com'.split())
# execute('scrapy crawl h2o-china.com'.split())
# execute('scrapy crawl nahs.org.cn'.split())
# execute('scrapy crawl cpnn.com.cn'.split())
# execute('scrapy crawl 100ppi.com'.split())
# execute('scrapy crawl sinotex.cn'.split())
# execute('scrapy crawl boyar.cn'.split())
# execute('scrapy crawl zhuwang.cc'.split())
# execute('scrapy crawl bjx.com.cn'.split())
# execute('scrapy crawl chuneng.bjx.com.cn'.split())
# execute('scrapy crawl shoudian.bjx.com.cn'.split())
# execute('scrapy crawl huanbao.bjx.com.cn'.split())
# execute('scrapy crawl guangfu.bjx.com.cn'.split())
# execute('scrapy crawl shupeidian.bjx.com.cn'.split())
# execute('scrapy crawl evpartner.com'.split())
# execute('scrapy crawl zyzhan.com'.split())
# execute('scrapy crawl gas.in-en.com'.split())
# execute('scrapy crawl cww.net.cn'.split())
# execute('scrapy crawl ccidcom.com'.split())
# execute('scrapy crawl powerpigs.net'.split())
# execute('scrapy crawl cableabc.com'.split())
# execute('scrapy crawl cnal.com'.split())
# execute('scrapy crawl cec1979.org.cn'.split())
# execute('scrapy crawl ledinside.cn'.split())
# execute('scrapy crawl 10000link.com'.split())
# execute('scrapy crawl shoujibao.cn'.split())
# execute('scrapy crawl cceep.com'.split())
# execute('scrapy crawl zol.com.cn'.split())
# execute('scrapy crawl jrtzb.com.cn'.split())
# execute('scrapy crawl 21-sun.com'.split())
# execute('scrapy crawl paper.com.cn'.split())
# execute('scrapy crawl chemnet.com'.split())
# execute('scrapy crawl chinatimes.net.cn'.split())
# execute('scrapy crawl cheari.com'.split())
# execute('scrapy crawl xuangubao.cn'.split())
# execute('scrapy crawl 24k99.com'.split())
# execute('scrapy crawl canyin88.com'.split())
# execute('scrapy crawl csi.com.cn'.split())
# execute('scrapy crawl cankaoxiaoxi.com'.split())
# execute('scrapy crawl tjkx.com'.split())
# execute('scrapy crawl gongkong.com'.split())
# execute('scrapy crawl sxcoal.com'.split())
# execute('scrapy crawl ccmn.cn'.split())
# execute('scrapy crawl egsea.com'.split())
# execute('scrapy crawl fx678.com'.split())
# execute('scrapy crawl luxe.co'.split())#减速爬取
# execute('scrapy crawl meadin.com'.split())
# execute('scrapy crawl chemall.com.cn'.split())
# execute('scrapy crawl ucheke.jrj.com.cn'.split())
# execute('scrapy crawl traveldaily.cn'.split())
# execute('scrapy crawl 21jingji.com'.split())
# execute('scrapy crawl chinacef.cn'.split())
# execute('scrapy crawl dt.sxgov.cn'.split())
# execute('scrapy crawl eefocus.com'.split())
# execute('scrapy crawl ebrun.com'.split())
# execute('scrapy crawl ifnews.com'.split())
# execute('scrapy crawl carnoc.com'.split())
# execute('scrapy crawl henan.china.com'.split())
# execute('scrapy crawl factory.mysteel.com'.split())
# execute('scrapy crawl cqnews.net'.split())
# execute('scrapy crawl insurance.cngold.org'.split())
# execute('scrapy crawl huanqiu.com'.split())
# execute('scrapy crawl 365jia.cn'.split())
# execute('scrapy crawl jrh.financeun.com'.split())#降速爬取
# execute('scrapy crawl cf40.org.cn'.split())
# execute('scrapy crawl investorchina.cn'.split())
# execute('scrapy crawl semi.org.cn'.split())
# execute('scrapy crawl nfncb.cn'.split())
# execute('scrapy crawl mei.net.cn'.split())
# execute('scrapy crawl zgnjw.com.cn'.split())
# execute('scrapy crawl mutongzixun.com'.split())
# execute('scrapy crawl chinagrain.cn'.split())
# execute('scrapy crawl chnfund.com'.split())
# execute('scrapy crawl zgyhy.com.cn'.split())
# execute('scrapy crawl jdw001.com'.split())
# execute('scrapy crawl gg-lb.com'.split())
# execute('scrapy crawl cnii.com.cn'.split())
# execute('scrapy crawl dcement.com'.split())
# execute('scrapy crawl zgw.com'.split())
# execute('scrapy crawl cec.org.cn'.split())
# execute('scrapy crawl cpcaauto.com'.split())
# execute('scrapy crawl portcontainer.com'.split())
# execute('scrapy crawl chinabond.com.cn'.split())
# execute('scrapy crawl eetop.cn'.split())
# execute('scrapy crawl jiankangad.com'.split())#降速爬取
# execute('scrapy crawl crcc.cn'.split())
# execute('scrapy crawl cpppc.org'.split())
# execute('scrapy crawl cnautonews.com'.split())
# execute('scrapy crawl chinanews.com.cn'.split())
# execute('scrapy crawl port.org.cn'.split())
# execute('scrapy crawl escn.com.cn'.split())
# execute('scrapy crawl chineseshipping.com.cn'.split())
# execute('scrapy crawl jjckb.cn'.split())
# execute('scrapy crawl financialnews.com.cn'.split())
# execute('scrapy crawl cbt.com.cn'.split())
# execute('scrapy crawl cnmn.com.cn'.split())
# execute('scrapy crawl moer.cn'.split())
# execute('scrapy crawl huanqiunet.com.cn'.split())
# execute('scrapy crawl ceeh.com.cn'.split())
# execute('scrapy crawl sznews.com'.split())
# execute('scrapy crawl csia.net.cn '.split())
# execute('scrapy crawl caiguu.com'.split())
# execute('scrapy crawl zhidx.com'.split())
# execute('scrapy crawl km.eeju.com'.split())
# execute('scrapy crawl gscn.com.cn'.split())
# execute('scrapy crawl etlong.com'.split())
# execute('scrapy crawl fccs.com'.split())
# execute('scrapy crawl dxwfgg.com'.split())
# execute('scrapy crawl ihanhua.com'.split())
# execute('scrapy crawl focus.cn'.split())
# execute('scrapy crawl 0416.055x.com'.split())
# execute('scrapy crawl jm.loupan.com'.split())
# execute('scrapy crawl gjjmxy.lixin.edu.cn'.split())
# execute('scrapy crawl gdjt.stecol.cn'.split())
# execute('scrapy crawl mbahome.com'.split())
# execute('scrapy crawl china.com.cn'.split())
# execute('scrapy crawl als.nmgnews.com.cn'.split())
# execute('scrapy crawl bgl.n3.com.cn'.split())
# execute('scrapy crawl dnw.com.cn'.split())
# execute('scrapy crawl srq.n3.com.cn'.split())
# execute('scrapy crawl rmsznet.com'.split())
# execute('scrapy crawl hzp.36hjob.com'.split())
# execute('scrapy crawl edu.zjol.com.cn'.split())
# execute('scrapy crawl ce.cri.cn'.split())
# execute('scrapy crawl gr.crionline.cn'.split())
# execute('scrapy crawl scol.com.cn'.split())
# execute('scrapy crawl hbfp.cnhubei.com'.split())
# execute('scrapy crawl ja.ybxww.com'.split())
# execute('scrapy crawl heilongjiang.okcis.cn'.split())
# execute('scrapy crawl cnxiantao.com'.split())
# execute('scrapy crawl cwcg.cscec.com'.split())
# execute('scrapy crawl jzj.36hjob.com'.split())
# execute('scrapy crawl kfq.jcs.gov.cn'.split())
# execute('scrapy crawl facaicao.com'.split())
# execute('scrapy crawl gg.36hjob.com'.split())
execute('scrapy crawl cnfol.hk.com'.split())











#
#
#
#
# for item in ['caam.org.cn','zhiding.cn','800hr.com']:
# 	execute(str('scrapy crawl '+item).split())